export const data = [
  {
    id: 1,
    img: "https://lh6.googleusercontent.com/-VrqOCWFewiI/Tmd_MhH85FI/AAAAAAAAF7k/E7Ahfc0Mlq0/s800/war2peace.jpg",
    name: "War and Peace",
    author: "L. N. Tolstoy",
    category: "Novel",
  },
  {
    id: 2,
    img: "https://www.mycozyclassics.com/wp-content/uploads/2012/06/Cozy-Classics-Pride-and-Prejudice-large-1.jpg",
    name: "Pride and Prejudaice",
    author: "Jane Austen",
    category: "Novel",
  },
  {
    id: 3,
    img: "https://m.media-amazon.com/images/I/81FMfUBCE8L._SL1500_.jpg",
    name: "Alice in wonderland",
    author: "Lewis Carroll",
    category: "Novel",
  },
  {
    id: 4,
    img: "https://rowman.com/L/14/985/9781498568111.jpg",
    name: "Foreign wars on U.S.",
    author: "Robert W. Tomlinson",
    category: "Novel",
  },
  {
    id: 5,
    img: "https://media.npr.org/assets/img/2022/04/29/rose_final_final-002-_custom-27d03cc4169ace6d598aa1b027a3f4b682745ae9-s1100-c50.jpg",
    name: "Run Rose run",
    author: "Dolly Parton and James Patterson",
    category: "Novel",
  },
  {
    id: 6,
    img: "https://images-na.ssl-images-amazon.com/images/I/71ZLx1RVhSL.jpg",
    name: "The Giant book of poetry",
    author: "William Roetzheim",
    category: "Poem",
  },
  {
    id: 7,
    img: "https://www.kidscanpress.com/sites/default/files/products/poem_in_my_pocket.jpg",
    name: "Poem in my pocket",
    author: "Chris Tougas",
    category: "Poem",
  },
  {
    id: 8,
    img: "https://www.press.umich.edu/images/covers/full/9780472132393.jpg",
    name: "Ancient latin poetry books",
    author: "Gabriel Nocchi Macedo",
    category: "Poem",
  },
  {
    id: 9,
    img: "https://gallerypress.com/dev/wp-content/uploads/2021/08/Mahon-The-Poems-HBK.jpg",
    name: "The poems",
    author: "Derek Mahon",
    category: "Poem",
  },
  {
    id: 10,
    img: "https://www.graywolfpress.org/sites/default/files/styles/book_cover_large/public/covers/9781555976903.png?itok=Vui2Y70E",
    name: "Citizen",
    author: "Claudia Rankine",
    category: "Poem",
  },
  {
    id: 11,
    img: "https://i.kinja-img.com/gawker-media/image/upload/c_scale,f_auto,fl_progressive,pg_1,q_80,w_800/9ff5c54849430139c835f03f771df35a.png",
    name: "Half Sick of Shadow",
    author: "Laura Sebastian",
    category: "Fantasy",
  },
  {
    id: 12,
    img: "https://static01.nyt.com/images/2020/05/24/books/00SixofCrows/6084abf592fb4414a9c1bad886cf5f52-jumbo.jpg",
    name: "Six of Crows",
    author: "Leigh Bardugo",
    category: "Fantasy",
  },
  {
    id: 13,
    img: "https://www.themarysue.com/wp-content/uploads/2022/04/1-2.jpg",
    name: "A Discovery of Witches",
    author: "Deborah Harkness",
    category: "Fantasy",
  },
  {
    id: 14,
    img: "https://i.kinja-img.com/gawker-media/image/upload/c_scale,f_auto,fl_progressive,pg_1,q_80,w_800/b410fbdb54e64b4cda31fe66c4f4b377.jpg",
    name: "House of Sky and Breath",
    author: "Sarah J. Maas",
    category: "Fantasy",
  },
  {
    id: 15,
    img: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1579226799l/40381319._SY475_.jpg",
    name: "The Priory of the Orange",
    author: "Samantha Shannon",
    category: "Fantasy",
  },
  {
    id: 16,
    img: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781499811247/the-thieving-collectors-of-fine-childrens-books-9781499811247_hr.jpg",
    name: "The thieving collectors of fine childrens books",
    author: "Adam Perry",
    category: "children's literature",
  },
  {
    id: 17,
    img: "https://img.huffingtonpost.com/asset/5f38b9e61f00005204339c23.png?ops=scalefit_960_noupscale",
    name: "Abigail the whale",
    author: "David Cali & Sanja Bougaeva",
    category: "children's literature",
  },
  {
    id: 18,
    img: "https://africainwords.files.wordpress.com/2014/01/giraffes.jpg",
    name: "Giraffes can't dance",
    author: "Giles Andrese & Guy Parker-Rees",
    category: "children's literature",
  },
  {
    id: 19,
    img: "https://m.media-amazon.com/images/I/515CYUgG2nL.jpg",
    name: "Twinkle, the funny Unicorn",
    author: "Lindsey Scott",
    category: "children's literature",
  },
  {
    id: 20,
    img: "https://www.penguin.co.uk/content/dam/prh/books/110/1101249/9781408416655.jpg.transform/PRHDesktopWide_small/image.jpg",
    name: "Paddington",
    author: "Michael Bond",
    category: "children's literature",
  },
  {
    id: 21,
    img: "https://i.insider.com/5cd1f8f193a1520b0150e7b6?width=1000&format=jpeg&auto=webp",
    name: "If i run the zoo",
    author: "Dr. Seuss",
    category: "children's literature",
  },
];
